version: '3'

services:
  app:
    build:
      context: ./
    expose:
      - 4000
    environment:
      GOPENCOV_DB_DRIVER: "postgres"
      GOPENCOV_DB_URI: "postgres://gopencov:gopencov@postgresql/gopencov?sslmode=disable"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: gopencov
      POSTGRES_PASSWORD: gopencov
    ports:
      - 5555:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
